//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: myproto.proto
namespace pb
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"C2GSHeartTick")]
  public partial class C2GSHeartTick : global::ProtoBuf.IExtensible
  {
    public C2GSHeartTick() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"C2GSHeartTickRet")]
  public partial class C2GSHeartTickRet : global::ProtoBuf.IExtensible
  {
    public C2GSHeartTickRet() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"C2GASLogin")]
  public partial class C2GASLogin : global::ProtoBuf.IExtensible
  {
    public C2GASLogin() {}
    
    private string _AccountName = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"AccountName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string AccountName
    {
      get { return _AccountName; }
      set { _AccountName = value; }
    }
    private string _Password = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"Password", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Password
    {
      get { return _Password; }
      set { _Password = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GAS2CLoginRet")]
  public partial class GAS2CLoginRet : global::ProtoBuf.IExtensible
  {
    public GAS2CLoginRet() {}
    
    private pb.GAS2CLoginRet.ErrorCode _RetCode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"RetCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public pb.GAS2CLoginRet.ErrorCode RetCode
    {
      get { return _RetCode; }
      set { _RetCode = value; }
    }
    private string _AccountName = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"AccountName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string AccountName
    {
      get { return _AccountName; }
      set { _AccountName = value; }
    }
    private bool _HasRole = default(bool);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"HasRole", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool HasRole
    {
      get { return _HasRole; }
      set { _HasRole = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"ErrorCode")]
    public enum ErrorCode
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOGIN_SUCCESS", Value=1)]
      LOGIN_SUCCESS = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOGIN_FAIL", Value=2)]
      LOGIN_FAIL = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOGIN_ACCOUNTNAME_ERR", Value=3)]
      LOGIN_ACCOUNTNAME_ERR = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOGIN_PWD_ERR", Value=4)]
      LOGIN_PWD_ERR = 4
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"C2GASRegister")]
  public partial class C2GASRegister : global::ProtoBuf.IExtensible
  {
    public C2GASRegister() {}
    
    private string _AccountName = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"AccountName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string AccountName
    {
      get { return _AccountName; }
      set { _AccountName = value; }
    }
    private string _Password = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"Password", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Password
    {
      get { return _Password; }
      set { _Password = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GAS2CRegisterRet")]
  public partial class GAS2CRegisterRet : global::ProtoBuf.IExtensible
  {
    public GAS2CRegisterRet() {}
    
    private pb.GAS2CRegisterRet.ErrorCode _RetCode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"RetCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public pb.GAS2CRegisterRet.ErrorCode RetCode
    {
      get { return _RetCode; }
      set { _RetCode = value; }
    }
    private string _AccountName = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"AccountName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string AccountName
    {
      get { return _AccountName; }
      set { _AccountName = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"ErrorCode")]
    public enum ErrorCode
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOGIN_SUCCESS", Value=1)]
      LOGIN_SUCCESS = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOGIN_FAIL_ACCOUNTEXIST", Value=2)]
      LOGIN_FAIL_ACCOUNTEXIST = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOGIN_FAIL", Value=3)]
      LOGIN_FAIL = 3
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"C2GSRequestRoleInfo")]
  public partial class C2GSRequestRoleInfo : global::ProtoBuf.IExtensible
  {
    public C2GSRequestRoleInfo() {}
    
    private string _AccountName = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"AccountName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string AccountName
    {
      get { return _AccountName; }
      set { _AccountName = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RoleInfo")]
  public partial class RoleInfo : global::ProtoBuf.IExtensible
  {
    public RoleInfo() {}
    
    private int _RoleType = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"RoleType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int RoleType
    {
      get { return _RoleType; }
      set { _RoleType = value; }
    }
    private int _RoleLev = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"RoleLev", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int RoleLev
    {
      get { return _RoleLev; }
      set { _RoleLev = value; }
    }
    private string _RoleName = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"RoleName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string RoleName
    {
      get { return _RoleName; }
      set { _RoleName = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GS2CRequestRoleInfoRet")]
  public partial class GS2CRequestRoleInfoRet : global::ProtoBuf.IExtensible
  {
    public GS2CRequestRoleInfoRet() {}
    
    private string _AccountName = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"AccountName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string AccountName
    {
      get { return _AccountName; }
      set { _AccountName = value; }
    }
    private readonly global::System.Collections.Generic.List<pb.RoleInfo> _RoleInfoList = new global::System.Collections.Generic.List<pb.RoleInfo>();
    [global::ProtoBuf.ProtoMember(2, Name=@"RoleInfoList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<pb.RoleInfo> RoleInfoList
    {
      get { return _RoleInfoList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"C2GSEnterGame")]
  public partial class C2GSEnterGame : global::ProtoBuf.IExtensible
  {
    public C2GSEnterGame() {}
    
    private string _AccountName = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"AccountName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string AccountName
    {
      get { return _AccountName; }
      set { _AccountName = value; }
    }
    private pb.RoleInfo _SelectedRoleInfo = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"SelectedRoleInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public pb.RoleInfo SelectedRoleInfo
    {
      get { return _SelectedRoleInfo; }
      set { _SelectedRoleInfo = value; }
    }
    private bool _IsNewRole = default(bool);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"IsNewRole", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool IsNewRole
    {
      get { return _IsNewRole; }
      set { _IsNewRole = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GS2CEnterGameRet")]
  public partial class GS2CEnterGameRet : global::ProtoBuf.IExtensible
  {
    public GS2CEnterGameRet() {}
    
    private string _AccountName = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"AccountName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string AccountName
    {
      get { return _AccountName; }
      set { _AccountName = value; }
    }
    private pb.GS2CEnterGameRet.ErrorCode _RetCode;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"RetCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public pb.GS2CEnterGameRet.ErrorCode RetCode
    {
      get { return _RetCode; }
      set { _RetCode = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"ErrorCode")]
    public enum ErrorCode
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ENTER_SUCCESS", Value=1)]
      ENTER_SUCCESS = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ENTER_FAIL", Value=2)]
      ENTER_FAIL = 2
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GS2CRoleDetailInfo")]
  public partial class GS2CRoleDetailInfo : global::ProtoBuf.IExtensible
  {
    public GS2CRoleDetailInfo() {}
    
    private string _AccountName = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"AccountName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string AccountName
    {
      get { return _AccountName; }
      set { _AccountName = value; }
    }
    private pb.RoleInfo _SelectedRoleInfo = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"SelectedRoleInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public pb.RoleInfo SelectedRoleInfo
    {
      get { return _SelectedRoleInfo; }
      set { _SelectedRoleInfo = value; }
    }
    private int _Exp = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"Exp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Exp
    {
      get { return _Exp; }
      set { _Exp = value; }
    }
    private int _Money = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"Money", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Money
    {
      get { return _Money; }
      set { _Money = value; }
    }
    private int _Diamond = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"Diamond", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Diamond
    {
      get { return _Diamond; }
      set { _Diamond = value; }
    }
    private int _VIP = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"VIP", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int VIP
    {
      get { return _VIP; }
      set { _VIP = value; }
    }
    private readonly global::System.Collections.Generic.List<pb.EquipmentData> _EquipmentDataList = new global::System.Collections.Generic.List<pb.EquipmentData>();
    [global::ProtoBuf.ProtoMember(7, Name=@"EquipmentDataList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<pb.EquipmentData> EquipmentDataList
    {
      get { return _EquipmentDataList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EquipmentData")]
  public partial class EquipmentData : global::ProtoBuf.IExtensible
  {
    public EquipmentData() {}
    
    private int _OID = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"OID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int OID
    {
      get { return _OID; }
      set { _OID = value; }
    }
    private int _ConfigID = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"ConfigID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int ConfigID
    {
      get { return _ConfigID; }
      set { _ConfigID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}